name: trymd_partner
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

   
      
  auto_size_text: 3.0.0
  cached_network_image: 3.1.0+1
  font_awesome_flutter: 8.11.0
  google_fonts: 2.1.0
  intl: 0.17.0
  json_path: 0.2.1
  page_transition: 2.0.4
  shared_preferences: 
  timeago: 3.1.0
  url_launcher: 6.0.15
  rename: 
  path_provider: ^2.0.1
 
   


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_svg: ^1.0.3
  pin_code_fields: ^7.3.0
  flutter_search_bar: ^2.1.0
  multi_select_item: ^1.0.3
  flutter_rounded_date_picker: ^2.0.2
  flutter_staggered_grid_view: ^0.6.1
  staggered_grid_view_flutter: ^0.0.4
  animated_check: 
  image_picker: 
  date_field:
  fluttertoast: 
  cool_alert:
  flutter_switch:
  localstore:
  localstorage: ^4.0.0+1
  geolocator: ^8.0.5
  google_maps_flutter:
  geocoding:
  flutter_google_places_hoc081098: ^1.0.1
  dotted_line:
  accordion:
  email_validator:
  firebase_messaging:
  firebase_analytics:
  flutter_barcode_scanner: ^2.0.0
  razorpay_flutter: ^1.2.9
  percent_indicator: ^4.0.0
  table_calendar: 
  pie_chart: ^5.3.0
  date_format: ^2.0.5
  flutter_calendar_carousel:
  flutter_time_picker_spinner: ^2.0.0
  hexcolor: 
  line_icons: ^2.0.1
  expansion_tile_card: ^2.0.0
  google_nav_bar: ^5.0.6
  smooth_page_indicator: ^1.0.0+2
  date_time_picker: ^2.1.0
  flutter_local_notifications: ^9.4.0
  easy_debounce: ^2.0.2+1
  audioplayers: ^0.20.1
  flutter_neumorphic: ^3.2.0
  assets_audio_player: ^3.0.4+1
  record: ^4.0.2
 


dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  firebase_crashlytics_platform_interface: 3.1.13
  cloud_firestore_platform_interface: 5.4.13
  firebase_auth_platform_interface: 6.1.11
  firebase_storage_platform_interface: 4.0.14
  cloud_functions_platform_interface: 5.0.21
  firebase_analytics_platform_interface: 3.0.5
  firebase_remote_config_platform_interface: 1.0.5
  firebase_dynamic_links_platform_interface: 0.2.0+5
  firebase_performance_platform_interface: 0.1.0+5
  firebase_app_installations_platform_interface: 0.1.0+6






dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/logo_final.png
    - assets/audios/
    - assets/jsonfile/

  fonts: 
    - 
      family: "geometric sans-serif"
      fonts: 
        - 
          asset: "assets/fonts/HarmoniasansBold.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "assets/fonts/HarmoniasansRegular.ttf"
          style: "normal"
          weight: 300
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "assets/fonts/Poppins-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "assets/fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "assets/fonts/Poppins-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "assets/fonts/Poppins-300.ttf"
          style: "normal"
          weight: 300
        - 
          asset: "assets/fonts/Poppins-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Comfortaa"
      fonts: 
        - 
          asset: "assets/fonts/Comfortaa-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "assets/fonts/Comfortaa-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Roboto"
      fonts: 
        - 
          asset: "assets/fonts/Roboto-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "assets/fonts/Roboto-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Lato"
      fonts: 
        - 
          asset: "assets/fonts/Lato-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Average Sans"
      fonts: 
        - 
          asset: "assets/fonts/AverageSans-regular.ttf"
          style: "normal"
          weight: 400
    # - 
    #   family: Harmonia Sans
    #   fonts:
    #     - 
    #       asset: "assets/fonts/Harmonia Sans W01 Bold.ttf"
    #       style: "normal"
    #       weight: 500
    #     - 
    #       asset: "assets/fonts/Harmonia Sans W01 Regular.ttf"
    #       style: "normal"
    #       weight: 300
        
 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/logo.png"